/*
 *
 * System constants
 *
 */

export const GET_LOCATIONS_REQUEST = 'app/System/GET_LOCATIONS_REQUEST';
export const GET_LOCATIONS_SUCCESS = 'app/System/GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_ERROR = 'app/System/GET_LOCATIONS_ERROR';

export const ADD_LOCATION_REQUEST = 'app/System/ADD_LOCATION_REQUEST';
export const ADD_LOCATION_SUCCESS = 'app/System/ADD_LOCATION_SUCCESS';
export const ADD_LOCATION_ERROR = 'app/System/ADD_LOCATION_ERROR';

export const UPDATE_LOCATION_RATE_REQUEST = 'app/System/UPDATE_LOCATION_RATE_REQUEST';
export const UPDATE_LOCATION_RATE_SUCCESS = 'app/System/UPDATE_LOCATION_RATE_SUCCESS';
export const UPDATE_LOCATION_RATE_ERROR = 'app/System/UPDATE_LOCATION_RATE_ERROR';

export const DISMISS = 'app/System/DISMISS';
