/*
 *
 * Dashboard constants
 *
 */

export const GET_ORGANIZATION_EVENTS_REQUEST = 'app/Dashboard/GET_ORGANIZATION_EVENTS_REQUEST';
export const GET_ORGANIZATION_EVENTS_SUCCESS = 'app/Dashboard/GET_ORGANIZATION_EVENTS_SUCCESS';
export const GET_ORGANIZATION_EVENTS_ERROR = 'app/Dashboard/GET_ORGANIZATION_EVENTS_ERROR';

export const GET_CLIENT_EVENTS_REQUEST = 'app/Dashboard/GET_CLIENT_EVENTS_REQUEST';
export const GET_CLIENT_EVENTS_SUCCESS = 'app/Dashboard/GET_CLIENT_EVENTS_SUCCESS';
export const GET_CLIENT_EVENTS_ERROR = 'app/Dashboard/GET_CLIENT_EVENTS_ERROR';

export const GET_ORGANIZATION_ANALYTICS_REQUEST = 'app/Dashboard/GET_ORGANIZATION_ANALYTICS_REQUEST';
export const GET_ORGANIZATION_ANALYTICS_SUCCESS = 'app/Dashboard/GET_ORGANIZATION_ANALYTICS_SUCCESS';
export const GET_ORGANIZATION_ANALYTICS_ERROR = 'app/Dashboard/GET_ORGANIZATION_ANALYTICS_ERROR';

export const DOWNLOAD_EVENT_REPORT_REQUEST = 'app/Dashboard/DOWNLOAD_EVENT_REPORT_REQUEST';
export const DOWNLOAD_EVENT_REPORT_SUCCESS = 'app/Dashboard/DOWNLOAD_EVENT_REPORT_SUCCESS';
export const DOWNLOAD_EVENT_REPORT_ERROR = 'app/Dashboard/DOWNLOAD_EVENT_REPORT_ERROR';

export const GET_CLIENT_ANALYTICS_REQUEST = 'app/Dashboard/GET_CLIENT_ANALYTICS_REQUEST';
export const GET_CLIENT_ANALYTICS_SUCCESS = 'app/Dashboard/GET_CLIENT_ANALYTICS_SUCCESS';
export const GET_CLIENT_ANALYTICS_ERROR = 'app/Dashboard/GET_CLIENT_ANALYTICS_ERROR';

export const GET_CLIENTS_REQUEST = 'app/Dashboard/GET_CLIENTS_REQUEST';
export const GET_CLIENTS_SUCCESS = 'app/Dashboard/GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_ERROR = 'app/Dashboard/GET_CLIENTS_ERROR';
