/*
 *
 * Events constants
 *
 */

export const DEFAULT_ACTION = 'app/Events/DEFAULT_ACTION';

export const GET_EVENTS_REQUEST = 'app/Events/GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'app/Events/GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'app/Events/GET_EVENTS_ERROR';

export const GET_ROLES_REQUEST = 'app/Events/GET_ROLES_REQUEST';
export const GET_ROLES_SUCCESS = 'app/Events/GET_ROLES_SUCCESS';
export const GET_ROLES_ERROR = 'app/Events/GET_ROLES_ERROR';

export const GET_PRODUCTS_REQUEST = 'app/Events/GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'app/Events/GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'app/Events/GET_PRODUCTS_ERROR';

export const ADD_EVENT_PRODUCTS_REQUEST = 'app/Events/ADD_EVENT_PRODUCTS_REQUEST';
export const ADD_EVENT_PRODUCTS_SUCCESS = 'app/Events/ADD_EVENT_PRODUCTS_SUCCESS';
export const ADD_EVENT_PRODUCTS_ERROR = 'app/Events/ADD_EVENT_PRODUCTS_ERROR';

export const ADD_EVENT_CONDITION_REQUEST = 'app/Events/ADD_EVENT_CONDITION_REQUEST';
export const ADD_EVENT_CONDITION_SUCCESS = 'app/Events/ADD_EVENT_CONDITION_SUCCESS';
export const ADD_EVENT_CONDITION_ERROR = 'app/Events/ADD_EVENT_CONDITION_ERROR';

export const REMOVE_EVENT_PRODUCTS_REQUEST = 'app/Events/REMOVE_EVENT_PRODUCTS_REQUEST';
export const REMOVE_EVENT_PRODUCTS_SUCCESS = 'app/Events/REMOVE_EVENT_PRODUCTS_SUCCESS';
export const REMOVE_EVENT_PRODUCTS_ERROR = 'app/Events/REMOVE_EVENT_PRODUCTS_ERROR';

export const INVITE_GUEST_REQUEST = 'app/Events/INVITE_GUEST_REQUEST';
export const INVITE_GUEST_SUCCESS = 'app/Events/INVITE_GUEST_SUCCESS';
export const INVITE_GUEST_ERROR = 'app/Events/INVITE_GUEST_ERROR';

export const DELETE_GUEST_REQUEST = 'app/Events/DELETE_GUEST_REQUEST';
export const DELETE_GUEST_SUCCESS = 'app/Events/DELETE_GUEST_SUCCESS';
export const DELETE_GUEST_ERROR = 'app/Events/DELETE_GUEST_ERROR';

export const RESEND_EMAIL_REQUEST = 'app/Events/RESEND_EMAIL_REQUEST';
export const RESEND_EMAIL_SUCCESS = 'app/Events/RESEND_EMAIL_SUCCESS';
export const RESEND_EMAIL_ERROR = 'app/Events/RESEND_EMAIL_ERROR';
