/*
 *
 * Requisition constants
 *
 */

export const GET_REQUISITIONS_REQUEST = 'app/Requisition/GET_REQUISITIONS_REQUEST';
export const GET_REQUISITIONS_SUCCESS = 'app/Requisition/GET_REQUISITIONS_SUCCESS';
export const GET_REQUISITIONS_ERROR = 'app/Requisition/GET_REQUISITIONS_ERROR';

export const GET_CLIENT_PRODUCTS_REQUEST = 'app/Requisition/GET_CLIENT_PRODUCTS_REQUEST';
export const GET_CLIENT_PRODUCTS_SUCCESS = 'app/Requisition/GET_CLIENT_PRODUCTS_SUCCESS';
export const GET_CLIENT_PRODUCTS_ERROR = 'app/Requisition/GET_CLIENT_PRODUCTS_ERROR';

export const CREATE_REQUISITION_ORDER_REQUEST = 'app/Requisition/CREATE_REQUISITION_ORDER_REQUEST';
export const CREATE_REQUISITION_ORDER_SUCCESS = 'app/Requisition/CREATE_REQUISITION_ORDER_SUCCESS';
export const CREATE_REQUISITION_ORDER_ERROR = 'app/Requisition/CREATE_REQUISITION_ORDER_ERROR';

export const DELETE_REQUISITION_ORDER_REQUEST = 'app/Requisition/DELETE_REQUISITION_ORDER_REQUEST';
export const DELETE_REQUISITION_ORDER_SUCCESS = 'app/Requisition/DELETE_REQUISITION_ORDER_SUCCESS';
export const DELETE_REQUISITION_ORDER_ERROR = 'app/Requisition/DELETE_REQUISITION_ORDER_ERROR';
